# Task 4: Forecasting Model Development

## Objective

The objective of this task is to develop forecasting models for Ethiopia's financial inclusion indicators using the enriched dataset prepared in previous tasks. This notebook prepares the forecasting dataset, trains baseline and statistical forecasting models, evaluates model performance, and generates future forecasts that will be used in the dashboard developed in Task 5.

In [1]:
import warnings
warnings.filterwarnings("ignore")

from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error
)

from statsmodels.tsa.stattools import adfuller

plt.style.use("ggplot")

In [2]:
project_root = Path.cwd()

processed_path = project_root / "data" / "processed"

figures_path = project_root / "figures"

processed_path.mkdir(
    parents=True,
    exist_ok=True
)

figures_path.mkdir(
    parents=True,
    exist_ok=True
)

print(processed_path)

c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\notebooks\data\processed

In [3]:
from pathlib import Path

print(Path.cwd())

for file in Path.cwd().rglob("*.csv"):
    print(file)

c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\notebooks

In [4]:
from pathlib import Path

print("Current folder:")
print(Path.cwd())

print("\nSearching for CSV files...\n")

for f in Path.cwd().parent.rglob("*.csv"):
    print(f)

Current folder:
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\notebooks

Searching for CSV files...

c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\models\event_indicator_association_matrix.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\models\event_indicator_association_summary.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\tornado\test\csv_translations\fr_FR.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\vector_ar\tests\Matlab_results\test_coint.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\arima111_forecasts.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\arima212_forecast.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\ARMLEConstantPredict.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\AROLSConstantPredict.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\AROLSNoConstantPredict.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\bds_data.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\bds_results.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\gnpdef.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\rand10000.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\resids_css_c.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\resids_css_nc.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\resids_exact_c.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\resids_exact_nc.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\results_arima_exog_forecasts_css.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\results_arima_exog_forecasts_mle.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\results_arima_forecasts.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\results_arima_forecasts_all_css.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\results_arima_forecasts_all_css_diff.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\results_arima_forecasts_all_mle.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\results_arima_forecasts_all_mle_diff.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\results_arma_forecasts.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\results_ar_forecast_mle_dynamic.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\results_ccf.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\results_corrgram.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\rgnp.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\rgnpq.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\stkprc.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\yhat_css_c.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\yhat_css_nc.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\yhat_exact_c.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\yhat_exact_nc.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\tests\results\y_arma_data.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\stl\tests\results\mstl_elec_vic.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\stl\tests\results\mstl_test_results.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\stl\tests\results\stl_co2.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\stl\tests\results\stl_test_results.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\cfa_tvpvar_beta.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\cfa_tvpvar_invP.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\cfa_tvpvar_Omega_11.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\cfa_tvpvar_Omega_22.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\cfa_tvpvar_posterior_mean.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\cfa_tvpvar_S10.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\cfa_tvpvar_Si0.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\cfa_tvpvar_state_variates.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\cfa_tvpvar_v10.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\cfa_tvpvar_vi0.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\clark1989.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\exponential_smoothing_params.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\exponential_smoothing_predict.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\exponential_smoothing_states.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_clark1989_R.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_dynamic_factor_stata.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_exact_initial_common_level_R.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_exact_initial_common_level_restricted_R.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_exact_initial_dfm_R.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_exact_initial_local_level_R.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_exact_initial_local_linear_trend_missing_R.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_exact_initial_local_linear_trend_R.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_exact_initial_var1_measurement_error_R.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_exact_initial_var1_missing_R.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_exact_initial_var1_mixed_R.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_exact_initial_var1_R.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_intercepts_R.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_realgdpar_stata.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_sarimax_coverage.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_simulation_smoothing0.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_simulation_smoothing1.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_simulation_smoothing2.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_simulation_smoothing3.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_simulation_smoothing3_variates.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_simulation_smoothing4.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_simulation_smoothing5.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_simulation_smoothing6.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_smoothing2_R.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_smoothing3_R.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_smoothing_generalobscov_R.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_smoothing_R.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_varmax_stata.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_var_R_output.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_var_stata.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_wpi1_ar3_matlab_ssm.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_wpi1_ar3_stata.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\results_wpi1_missing_ar3_matlab_ssm.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\frbny_nowcast\Nowcasting\data\US\2016-06-29.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\statespace\tests\results\frbny_nowcast\Nowcasting\data\US\2016-07-29.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\regime_switching\tests\results\mar_filardo.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\regime_switching\tests\results\results_predict_fedfunds.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\regime_switching\tests\results\results_predict_rgnp.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\tsa\holtwinters\tests\results\housing-data.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\treatment\tests\results\cataneo2.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\stats\tests\results\binary_constrict.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\stats\tests\results\bootleg.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\stats\tests\results\contingency_table_r_results.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\stats\tests\results\framing.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\stats\tests\results\influence_measures_bool_R.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\stats\tests\results\influence_measures_R.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\stats\tests\results\results_influence_logit.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\stats\tests\results\wspec1.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\stats\tests\results\wspec2.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\stats\tests\results\wspec3.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\stats\tests\results\wspec4.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\sandbox\regression\tests\racd10data_with_transformed.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\regression\tests\results\dietox.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\regression\tests\results\lasso_data.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\regression\tests\results\lme00.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\regression\tests\results\lme01.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\regression\tests\results\lme02.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\regression\tests\results\lme03.csv
c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 11\ethiopia-fi-forecast\venv\Lib\site-packages\statsmodels\regression\tests\results\lme04.csv

In [5]:
import pandas as pd
from pathlib import Path

forecast_file = Path("../data/processed/ethiopia_fi_enriched.csv")

forecast_df = pd.read_csv(forecast_file)

forecast_df.head()

,category,collected_by,collection_date,comparable_country,confidence,evidence_basis,fiscal_year,gender,impact_direction,impact_estimate,...,region,related_indicator,relationship_type,source_name,source_type,source_url,unit,value_numeric,value_text,value_type
0,NaN,Bilen M. Gebremariam,2025-01-20,NaN,high,NaN,2014,all,NaN,NaN,...,NaN,NaN,NaN,Global Findex 2014,survey,https://www.worldbank.org/en/publication/globa...,%,22.0,NaN,percentage
1,NaN,Bilen M. Gebremariam,2025-01-20,NaN,high,NaN,2017,all,NaN,NaN,...,NaN,NaN,NaN,Global Findex 2017,survey,https://www.worldbank.org/en/publication/globa...,%,35.0,NaN,percentage
2,NaN,Bilen M. Gebremariam,2025-01-20,NaN,high,NaN,2021,all,NaN,NaN,...,NaN,NaN,NaN,Global Findex 2021,survey,https://www.worldbank.org/en/publication/globa...,%,46.0,NaN,percentage
3,NaN,Bilen M. Gebremariam,2025-01-20,NaN,high,NaN,2021,male,NaN,NaN,...,NaN,NaN,NaN,Global Findex 2021,survey,https://www.worldbank.org/en/publication/globa...,%,56.0,NaN,percentage
4,NaN,Bilen M. Gebremariam,2025-01-20,NaN,high,NaN,2021,female,NaN,NaN,...,NaN,NaN,NaN,Global Findex 2021,survey,https://www.worldbank.org/en/publication/globa...,%,36.0,NaN,percentage

In [6]:
print("Shape:", forecast_df.shape)

forecast_df.info()

forecast_df.describe(include="all")

Shape: (58, 35)
<class 'pandas.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 35 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   category             10 non-null     str
 1   collected_by         58 non-null     str
 2   collection_date      58 non-null     str
 3   comparable_country   7 non-null      str
 4   confidence           58 non-null     str
 5   evidence_basis       14 non-null     str
 6   fiscal_year          44 non-null     str
 7   gender               58 non-null     str
 8   impact_direction     14 non-null     str
 9   impact_estimate      12 non-null     float64
 10  impact_magnitude     14 non-null     str
 11  indicator            58 non-null     str
 12  indicator_code       44 non-null     str
 13  indicator_direction  34 non-null     str
 14  lag_months           14 non-null     float64
 15  location             58 non-null     str
 16  notes                15 non-null     str
 17  observation_date     58 non-null     str
 18  original_text        34 non-null     str
 19  parent_id            14 non-null     str
 20  period_end           11 non-null     str
 21  period_start         11 non-null     str
 22  pillar               48 non-null     str
 23  record_id            58 non-null     str
 24  record_type          58 non-null     str
 25  region               0 non-null      float64
 26  related_indicator    14 non-null     str
 27  relationship_type    14 non-null     str
 28  source_name          44 non-null     str
 29  source_type          44 non-null     str
 30  source_url           32 non-null     str
 31  unit                 48 non-null     str
 32  value_numeric        46 non-null     float64
 33  value_text           10 non-null     str
 34  value_type           58 non-null     str
dtypes: float64(4), str(31)
memory usage: 28.8 KB

,category,collected_by,collection_date,comparable_country,confidence,evidence_basis,fiscal_year,gender,impact_direction,impact_estimate,...,region,related_indicator,relationship_type,source_name,source_type,source_url,unit,value_numeric,value_text,value_type
count,10,58,58,7,58,14,44,58,14,12.000000,...,0.0,14,14,44,44,32,48,4.600000e+01,10,58
unique,7,1,2,4,2,3,14,3,2,NaN,...,NaN,9,3,26,7,9,9,NaN,3,6
top,product_launch,Bilen M. Gebremariam,2025-01-20,India,high,literature,2024,all,increase,NaN,...,NaN,USG_P2P_COUNT,direct,Global Findex 2021,operator,https://www.worldbank.org/en/publication/globa...,%,NaN,Launched,percentage
freq,2,58,57,3,45,7,12,54,12,NaN,...,NaN,3,9,5,15,10,27,NaN,7,29
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.416667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.770207e+10,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.048569,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.593717e+11,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-20.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.000000e+01,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.750000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.425000e+01,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.500000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.550000e+01,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.775000e+06,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.380000e+12,NaN,NaN

In [7]:
missing = (
    forecast_df
    .isnull()
    .sum()
    .sort_values(ascending=False)
)

missing[missing > 0]

region                 58
comparable_country     51
category               48
value_text             48
period_start           47
period_end             47
impact_estimate        46
impact_magnitude       44
relationship_type      44
impact_direction       44
evidence_basis         44
lag_months             44
related_indicator      44
parent_id              44
notes                  43
source_url             26
original_text          24
indicator_direction    24
source_type            14
fiscal_year            14
source_name            14
indicator_code         14
value_numeric          12
unit                   10
pillar                 10
dtype: int64

In [9]:
forecast_df["analysis_year"] = (
    pd.to_numeric(
        forecast_df["analysis_year"],
        errors="coerce"
    )
)

forecast_df = forecast_df.sort_values(
    "analysis_year"
)

forecast_df.head()

KeyError: 'analysis_year'

In [ ]:
account_df = forecast_df[
    forecast_df["indicator_code"] == "ACC_OWNERSHIP"
].copy()

account_df = account_df.sort_values(
    "analysis_year"
)

account_df[
    [
        "analysis_year",
        "value_numeric"
    ]
]

NameError: name 'forecast_df' is not defined

In [ ]:
plt.figure(figsize=(10,5))

plt.plot(
    account_df["analysis_year"],
    account_df["value_numeric"],
    marker="o",
    linewidth=2
)

plt.title(
    "Historical Account Ownership"
)

plt.xlabel("Year")

plt.ylabel("Percent")

plt.grid(True)

plt.tight_layout()

plt.savefig(
    figures_path /
    "historical_account_ownership.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

NameError: name 'account_df' is not defined

In [ ]:
train_size = int(
    len(account_df) * 0.8
)

train = account_df.iloc[:train_size]

test = account_df.iloc[train_size:]

print("Training observations:", len(train))

print("Testing observations:", len(test))

NameError: name 'account_df' is not defined

In [ ]:
plt.figure(figsize=(10,5))

plt.plot(
    train["analysis_year"],
    train["value_numeric"],
    marker="o",
    label="Training"
)

plt.plot(
    test["analysis_year"],
    test["value_numeric"],
    marker="o",
    label="Testing"
)

plt.title(
    "Training and Testing Split"
)

plt.xlabel("Year")

plt.ylabel("Account Ownership")

plt.legend()

plt.tight_layout()

plt.savefig(
    figures_path /
    "train_test_split.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

NameError: name 'train' is not defined

In [ ]:
adf_result = adfuller(
    account_df["value_numeric"]
)

print("ADF Statistic:", adf_result[0])

print("p-value:", adf_result[1])

if adf_result[1] < 0.05:
    print("Series is stationary.")
else:
    print("Series is not stationary.")

NameError: name 'adfuller' is not defined

In [ ]:
print("Forecast dataset loaded:", not forecast_df.empty)

print("Training rows:", len(train))

print("Testing rows:", len(test))

print(
    "Historical years:",
    account_df["analysis_year"].min(),
    "-",
    account_df["analysis_year"].max()
)

NameError: name 'forecast_df' is not defined

## Forecasting Model Development

This section develops forecasting models for the Account Ownership indicator. A baseline (Naïve) model is created and compared with an ARIMA forecasting model. Model performance is evaluated using MAE and RMSE to identify the most suitable forecasting approach.

In [ ]:
from statsmodels.tsa.arima.model import ARIMA

ModuleNotFoundError: No module named 'statsmodels'